@Library('mylib')_

pipeline
{
    agent any
    stages
    {
        stage('contDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('contBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.mavenBuild()
                }
            }
        }
        stage('contDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.tomcatDeploy("declerativePipelinewithSharedLibrary","172.31.17.140","testapp")
                }
            }
        }
        stage('contTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                    cicd.runSelenium("declerativePipelinewithSharedLibrary")
                }
            }
        }
        stage('contDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.tomcatDeploy("declerativePipelinewithSharedLibrary","172.31.22.185","prodapp")
                }
            }
        }
    }
}

